### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by RexWzh** [JuliaImages/QRDecoders.jl#14]
- [ ] Add supports for more complex pictures(most crucial).
- [ ] A closed codec system, i.e., all the pictures generated by QRCoders.jl (with all styles) can be decoded by this package.
- [ ] Improve performance of the decoding algorithm.
- [ ] Interact with other tools for QR codes.
